apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        name: techtrends
        ports:
        - containerPort: {{ .Values.containerport }} 
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe }}
            port: 3111
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe }}
            port: 3111
        resources:
{{ toYaml .Values.resources | indent 12 }}