apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-stage.yml
    path: helm/
    repoURL: https://github.com/veselinn16/tech-trends
    targetRevision: HEAD
